wandb_version: 1

_wandb:
  desc: null
  value:
    cli_version: 0.13.5
    framework: torch
    is_jupyter_run: false
    is_kaggle_kernel: false
    python_version: 3.9.12
    start_time: 1674503768.499813
    t:
      1:
      - 1
      - 55
      2:
      - 1
      - 55
      3:
      - 13
      - 16
      - 23
      4: 3.9.12
      5: 0.13.5
      8:
      - 4
      - 5
checkpoint:
  desc: null
  value: ''
cuda:
  desc: null
  value: false
entropy_coeff:
  desc: null
  value: 0.0
env_name:
  desc: null
  value: GridWorld-Default
eps_clip:
  desc: null
  value: 0.2
gamma:
  desc: null
  value: 0.99
gw_filepath:
  desc: null
  value: maps/test.txt
hidden_size:
  desc: null
  value: 64
lamda:
  desc: null
  value: 0.95
log_freq:
  desc: null
  value: 2500
lr:
  desc: null
  value: 0.0003
max_training_episodes:
  desc: null
  value: 500000
method:
  desc: null
  value: ppo
n_layers:
  desc: null
  value: 2
ppo_epochs:
  desc: null
  value: 20
save_model_freq:
  desc: null
  value: 0
seed:
  desc: null
  value: 0
update_every:
  desc: null
  value: 20
use_gae:
  desc: null
  value: true
value_loss_coeff:
  desc: null
  value: 0.25
