# @package _global_

agent:
  name: "ppo-hca"
  adv: "hca"
  value_loss_coeff: 0.0
  hca_checkpoint: ""
  hca_n_layers: 2
  hca_hidden_size: 128
  hca_lr: 3e-4
  env_steps_per_hca_update: 2048
  hca_epochs: 10
  hindsight_ratio_clip: null
  hca_batchsize: 256
  hca_dropout: 0
  hca_activation: "relu"
  hca_train_val_split: [0.9, 0.1]
  reset_hca: True

  # PPO
  env_steps_per_update: 2500
  ppo_epochs: 30
  eps_clip: 0.2
  entropy_coeff: 0.2
  n_layers: 2
  hidden_size: 64
  minibatch_size: 2500
  lr: 3e-4
  activation_fn: "relu"
  max_grad_norm: 0.5

