# @package _global_

env:
  name: "PongNoFrameskip-v4"
  type: "atari"
  sparse: false
  delay_reward: true
  gamma: 0.99
  max_steps: null

training:
  log_freq: 100  # Log every these many episodes
  save_model_freq: 0 # Save networks every these many episodes
  eval_freq: 500 # eval every these many episodes
  num_eval_eps: 10

agent:
  # several hyperparams from https://huggingface.co/ThomasSimonini/ppo-PongNoFrameskip-v4
  update_every_env_steps: 1024
  update_every: null
  ppo_epochs: 16
  value_loss_coeff: 0.5
  max_grad_norm: 0.5
  n_layers: 3
  hidden_size: 128
  eps_clip: 0.1
  lr: 3e-4
  lamda: 0.9
  entropy_coeff: 0.01
  hca_max_grad_norm: 10.0
  dd_max_grad_norm: 10.0
  r_max_grad_norm: 10.0
  r_normalize_targets: True
